spring:
  rabbitmq:
    host: localhost # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /yefeng # 虚拟主机
    username: yefeng # 用户名
    password: 123456 # 密码
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
#    publisher-returns: true # 开启publisher return机制